twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        titre: 'Convivial Event'
        home: '@App\Twig\HomeExtensions'

when@test:
    twig:
        strict_variables: true


