vich_uploader:
    db_driver: orm

    metadata:
        type: attribute 

    mappings:
        convivialevent_images:
            uri_prefix:         '%app.path.convivialevent_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.convivialevent_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false
