vich_uploader:
    db_driver: orm

    metadata:
        type: attribute 

    # mappings:
    #     page_images:
    #         uri_prefix: '%page_images%'
    #         upload_destination: '%kernel.project_dir%/public%page_images%'
    #         namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    #         inject_on_load: false
    #         delete_on_update: true
    #         delete_on_remove: true
    #     recipe_images:
    #         uri_prefix: '%recipe_images%'
    #         upload_destination: '%kernel.project_dir%/public%recipe_images%'
    #         namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    #         inject_on_load: false
    #         delete_on_update: true
    #         delete_on_remove: true
    #     homeblock_images:
    #         uri_prefix: '%homeblock_images%'
    #         upload_destination: '%kernel.project_dir%/public%homeblock_images%'
    #         namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    #         inject_on_load: false
    #         delete_on_update: true
    #         delete_on_remove: true