#!/bin/sh
. "$(dirname "$0")/husky.sh"

# Commit message
if ! head -n1 "$1" | grep -q "^\(fix/CE-\|feat/CE-\|hot-fix\)"; then
	echo ""
	echo "==== Commit stoppé : nommage incorrect ===="
	echo ""
	echo "Les messages de commit doivent tous commencer par : "
	echo "- fix/  suivi du numéro de ticket Trello (CE-001) pour les correctifs et de votre message"
	echo "- feat/ suivi du numéro de ticket Trello (CE-001) pour les nouvelles features et de votre message"
	echo "- hot-fix et de votre message"
	echo ""
	echo ""
	exit 1
fi

# Phpstan
cd $SCRIPT_DIR
cd ../../
vendor/phpstan/phpstan/phpstan analyse -c .husky/phpstan.neon
status=$?
if test $status -eq 0
then
	echo "phpstan OK"
else
	echo "phpstan KO"
	exit 1
fi

## Php cs fixer
cd $SCRIPT_DIR
cd ../
vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix src --dry-run --diff
status=$?
if test $status -eq 0
then
	echo "php-cs-fixer OK"
else
	echo "php-cs-fixer KO"
	exit 1
fi